-- CreateEnum
CREATE TYPE "FaseOrquestra" AS ENUM ('ENSAIO', 'RJM', 'CULTO', 'TROCA_INSTRUMENTO_CULTO', 'TROCA_INSTRUMENTO_OFICIALIZACAO', 'OFICIALIZACAO', 'OFICIALIZADO');

-- AlterTable
ALTER TABLE "alunos" ADD COLUMN "faseOrquestra" "FaseOrquestra" NOT NULL DEFAULT 'ENSAIO';
